services:
  theta-terminal-v3:
    container_name: theta-terminal-v3
    build:
      context: .
      dockerfile: Dockerfile
    image: theta-terminal-v3:latest 
    env_file:
      - .env
    environment:
      - THETADATAUSERNAME=${THETADATAUSERNAME}
      - THETADATAPASSWORD=${THETADATAPASSWORD}
    ports:
      - "25500:25500"
    restart: unless-stopped