name: Docker Build and Test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      env:
        THETADATAUSERNAME: ${{ secrets.THETADATAUSERNAME }}
        THETADATAPASSWORD: ${{ secrets.THETADATAPASSWORD }}
        THETATERMINALID: ${{ secrets.THETATERMINALID }}

      run: |
        make build
        # Wait for container to be healthy
        until docker compose ps | grep "Up"; do
          echo "Waiting for container..."
          sleep 5
        done
        make test
        
    - name: Check logs on failure
      if: failure()
      run: docker compose logs
      
    - name: Cleanup
      if: always()
      run: make down