name: Docker Build and Test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Build and test
      env:
        THETADATAUSERNAME: ${{ secrets.THETADATAUSERNAME }}
        THETADATAPASSWORD: ${{ secrets.THETADATAPASSWORD }}
        THETATERMINALID: ${{ secrets.THETATERMINALID }}

      run: |
        make build
        # Wait for container with max 10 attempts
        count=0
        until docker compose ps | grep "Up" || [ $count -eq 10 ]; do
          echo "Waiting for container... Attempt $((count+1))/10"
          sleep 10
          count=$((count+1))
        done
        if [ $count -eq 10 ]; then
          echo "Container failed to start after 10 attempts"
          docker compose logs
          exit 1
        fi
        make test
        
    - name: Check logs on failure
      if: failure()
      run: docker compose logs
      
    - name: Cleanup
      if: always()
      run: make down